version: "3.7"

networks:
  default:

volumes:
  data:

services:
  postgres:
    image: gstackutils
    volumes:
      - "data:/data"
      - ".:/src"
      - ".:/host"
    command: ["gstack", "start-postgres"]
    ports:
      - "127.0.0.1:5432:5432"
    env_file: ".env"
    tmpfs:
      - /run/

  django:
    image: gstackutils
    volumes:
      - "data:/data"
      - ".:/src"
      - ".:/host"
    command: ["gstack", "start-django"]
    depends_on: ["postgres"]
    ports:
      - "127.0.0.1:8000:8000"
    env_file: ".env"
    tmpfs:
      - /run/

  nginx:
    image: gstackutils
    volumes:
      - "data:/data"
      - ".:/src"
      - ".:/host"
    command: ["gstack", "start-nginx"]
    depends_on: ["django"]
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    env_file: ".env"
    tmpfs:
      - /run/

  main:
    build:
      context: docker
    image: gstackutils
    volumes:
      - ".:/src"
      - ".:/host"
    env_file: ".env"
    tmpfs:
      - /run/
