version: "3.7"

# volumes:
#   data:

networks:
  default:

services:
  # postgres:
  #   image: gstackutils
  #   volumes:
  #     - "data:/data"
  #     - ".:/src"
  #     - ".:/host"
  #   command: ["gstack", "db", "start"]
  #   ports:
  #     - 127.0.0.1:5432:5432

  main:
    build:
      context: docker
    image: gstackutils
    volumes:
      - ".:/src"
      - ".:/host"
      # - "data:/data"
