version: "3.7"

networks:
  default:

services:
  postgres:
    image: gstackutils
    volumes:
      - ".:/src"
      - ".:/host"
    command: ["gstack", "start", "postgres"]
    ports:
      - 127.0.0.1:5432:5432
    env_file: ".env"

  django:
    image: gstackutils
    volumes:
      - ".:/src"
      - ".:/host"
    command: ["gstack", "start", "django"]
    ports:
      - 127.0.0.1:80:8000
    env_file: ".env"

  main:
    build:
      context: docker
    image: gstackutils
    volumes:
      - ".:/src"
      - ".:/host"
    env_file: ".env"
