version: "3.7"

volumes:
  data:

networks:
  default:

services:
  postgres:
    image: gstackutils
    volumes:
      - "data:/data"
      - ".:/src"
      - ".:/host"
    command: ["gstack", "db", "start"]

  main:
    build:
      context: docker
    image: gstackutils
    volumes:
      - ".:/src"
      - ".:/host"
    command: ["gstack", "db", "wait", "-t", "9"]
